name: Build and Deploy
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        shell: bash
        run: |
          maven clean install
          docker build -t rootstech-classes
          docker push craftmaster2190/rootstech-classes
          curl -sS https://github.com/render-oss/render-cli/releases/download/v0.1.11/render-linux-x86_64 -o render-cli
